'use server';

/**
 * @fileOverview A Genkit flow for analyzing content to detect if it was AI-generated.
 *
 * - analyzeContentAuthenticity - A function that takes text or media and returns a likelihood of AI generation.
 * - ContentAuthenticityInput - The input type for the function.
 * - ContentAuthenticityOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ContentAuthenticityInputSchema = z.object({
  contentType: z.enum(['text', 'audio', 'video']),
  textContent: z.string().optional().describe('The text content to analyze.'),
  fileDataUri: z.string().optional().describe("A data URI of the audio or video file. Format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type ContentAuthenticityInput = z.infer<typeof ContentAuthenticityInputSchema>;

const ContentAuthenticityOutputSchema = z.object({
  aiLikelihood: z.number().min(0).max(100).describe('The percentage likelihood that the content is AI-generated (0-100).'),
  reasoning: z.string().describe('A concise explanation for the assessment.'),
});
export type ContentAuthenticityOutput = z.infer<typeof ContentAuthenticityOutputSchema>;

export async function analyzeContentAuthenticity(input: ContentAuthenticityInput): Promise<ContentAuthenticityOutput> {
  return contentAuthenticityFlow(input);
}

const prompt = ai.definePrompt({
  name: 'contentAuthenticityPrompt',
  input: {schema: ContentAuthenticityInputSchema},
  output: {schema: ContentAuthenticityOutputSchema},
  prompt: `You are an expert digital forensics analyst specializing in detecting AI-generated content. Analyze the provided input, which is of type '{{contentType}}'.

Based on the content, determine the likelihood that it was generated by an AI.

- For **text**, look for unnatural phrasing, lack of personal voice, generic statements, unusual consistency, or factual errors that an LLM might make.
- For **audio**, listen for synthetic or robotic tones, lack of natural cadence or emotional inflection, and unusual background noise or artifacts.
- For **video**, look for visual artifacts like unnatural facial movements (especially around the eyes and mouth), strange morphing, inconsistent lighting or shadows, and a "deepfake" quality.

Provide a percentage likelihood (aiLikelihood) from 0 to 100.
Provide a concise, bulleted list of reasons for your assessment (reasoning).

**Content to Analyze:**
{{#if textContent}}
--- TEXT ---
{{{textContent}}}
--- END TEXT ---
{{/if}}
{{#if fileDataUri}}
{{media url=fileDataUri}}
{{/if}}`,
});

const contentAuthenticityFlow = ai.defineFlow(
  {
    name: 'contentAuthenticityFlow',
    inputSchema: ContentAuthenticityInputSchema,
    outputSchema: ContentAuthenticityOutputSchema,
  },
  async input => {
    // Note: Video analysis can be slow and expensive.
    // The underlying model must support multimodal input for audio/video.
    // For this implementation, we assume a capable model is configured in genkit.
    const {output} = await prompt(input);
    return output!;
  }
);
