'use server';

/**
 * @fileOverview A Genkit flow for analyzing content to detect if it was AI-generated.
 *
 * - analyzeContentAuthenticity - A function that takes text or media and returns a likelihood of AI generation.
 * - ContentAuthenticityInput - The input type for the function.
 * - ContentAuthenticityOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ContentAuthenticityInputSchema = z.object({
  contentType: z.enum(['text', 'image', 'audio', 'video']),
  textContent: z.string().optional().describe('The text content to analyze.'),
  fileDataUri: z.string().optional().describe("A data URI of the image, audio, or video file. Format: 'data:<mimetype>;base64,<encoded_data>'."),
});
export type ContentAuthenticityInput = z.infer<typeof ContentAuthenticityInputSchema>;

const ContentAuthenticityOutputSchema = z.object({
  aiLikelihood: z.number().min(0).max(100).describe('The percentage likelihood that the content is AI-generated (0-100).'),
  reasoning: z.string().describe('A concise explanation for the assessment.'),
});
export type ContentAuthenticityOutput = z.infer<typeof ContentAuthenticityOutputSchema>;

export async function analyzeContentAuthenticity(input: ContentAuthenticityInput): Promise<ContentAuthenticityOutput> {
  return contentAuthenticityFlow(input);
}

const multimodalAuthenticityPrompt = ai.definePrompt({
  name: 'multimodalAuthenticityPrompt',
  input: {schema: ContentAuthenticityInputSchema},
  output: {schema: ContentAuthenticityOutputSchema},
  prompt: `You are an expert digital forensics analyst specializing in detecting AI-generated content. Analyze the provided input, which is of type '{{contentType}}'.

Based on the content, determine the likelihood that it was generated by an AI.

- For **text**, look for unnatural phrasing, lack of personal voice, generic statements, unusual consistency, or factual errors that an LLM might make.
- For **images**, look for artifacts common to AI generation, such as misshapen hands or limbs, strange textures, distorted text in the background, and an overly smooth or airbrushed appearance.
- For **audio**, listen for synthetic or robotic tones, lack of natural cadence or emotional inflection, and unusual background noise or artifacts.
- For **video**, look for visual artifacts like unnatural facial movements (especially around the eyes and mouth), strange morphing, inconsistent lighting or shadows, and a "deepfake" quality.

Provide a percentage likelihood (aiLikelihood) from 0 to 100.
Provide a concise, bulleted list of reasons for your assessment (reasoning).

**Content to Analyze:**
{{#if textContent}}
--- TEXT ---
{{{textContent}}}
--- END TEXT ---
{{/if}}
{{#if fileDataUri}}
{{media url=fileDataUri}}
{{/if}}`,
});

const imageAuthenticityPrompt = ai.definePrompt({
    name: 'imageAuthenticityPrompt',
    input: {schema: ContentAuthenticityInputSchema},
    output: {schema: ContentAuthenticityOutputSchema},
    prompt: `You are an expert digital forensics analyst specializing in detecting AI-generated images. Analyze the provided image.

Look for artifacts common to AI generation, such as:
- Misshapen hands, limbs, or faces
- Strange or inconsistent textures
- Distorted or nonsensical text in the background
- An overly smooth, "airbrushed", or plastic-like appearance
- Unnatural lighting, shadows, or reflections
- Odd blending or morphing between objects

Based on your analysis, provide a percentage likelihood (aiLikelihood) from 0 to 100 that this image was generated by an AI.
Also, provide a concise, bulleted list of reasons for your assessment (reasoning).

{{#if fileDataUri}}
{{media url=fileDataUri}}
{{/if}}
  `,
});


const contentAuthenticityFlow = ai.defineFlow(
  {
    name: 'contentAuthenticityFlow',
    inputSchema: ContentAuthenticityInputSchema,
    outputSchema: ContentAuthenticityOutputSchema,
  },
  async input => {
    // For images, use a more focused and potentially faster prompt.
    if (input.contentType === 'image' && input.fileDataUri) {
        const {output} = await imageAuthenticityPrompt(input);
        return output!;
    }
    
    // For other types, use the general multimodal prompt.
    // Note: Video analysis can be slow and expensive.
    const {output} = await multimodalAuthenticityPrompt(input);
    return output!;
  }
);
