'use client';

import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { LoaderCircle, Search, MapPin, AlertTriangle, Server } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { threatViewAction } from '@/app/actions';
import { type ThreatViewOutput } from '@/ai/flows/threat-view';

type HostResult = ThreatViewOutput['results'][0];

export function ThreatViewClient() {
  const [query, setQuery] = useState('port:21');
  const [isSearching, setIsSearching] = useState(false);
  const [results, setResults] = useState<HostResult[] | null>(null);
  const { toast } = useToast();

  const handleSearch = async () => {
    if (!query) {
      toast({
        variant: 'destructive',
        title: 'Query is required.',
      });
      return;
    }
    setIsSearching(true);
    setResults(null);

    const response = await threatViewAction({ query });

    if (response.success && response.data) {
      setResults(response.data.results);
      if (response.data.results.length === 0) {
        toast({
          title: 'No results found',
          description: `The AI couldn't generate any simulated results for "${query}".`,
        });
      }
    } else {
      toast({
        variant: 'destructive',
        title: 'Search Failed',
        description: response.error,
      });
    }

    setIsSearching(false);
  };

  return (
    <div className="space-y-8">
      <Card>
        <CardHeader>
          <CardTitle>ThreatView Search</CardTitle>
          <CardDescription>
            Simulate a Shodan-like search for exposed services. The AI will generate realistic but fictional examples based on your query.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex w-full max-w-lg items-center space-x-2">
            <Input
              type="text"
              placeholder="e.g., port:22, ProFTPD, MongoDB"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              disabled={isSearching}
              onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
            />
            <Button onClick={handleSearch} disabled={isSearching || !query}>
              {isSearching ? (
                <LoaderCircle className="animate-spin" />
              ) : (
                <Search />
              )}
              <span>{isSearching ? 'Searching...' : 'Search'}</span>
            </Button>
          </div>
        </CardContent>
      </Card>

      {isSearching && (
         <div className="flex flex-col items-center justify-center text-center p-8 space-y-4 rounded-lg border border-dashed">
            <LoaderCircle className="size-12 animate-spin text-primary" />
            <h3 className="text-xl font-semibold">Generating intelligence...</h3>
            <p className="text-muted-foreground">The AI is creating simulated host data based on your query.</p>
        </div>
      )}

      {results && results.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Simulated Results for "{query}"</CardTitle>
             <CardDescription>
              Showing {results.length} fictional examples generated by AI.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {results.map((result, index) => (
                <div key={index} className="p-4 border rounded-lg bg-card flex flex-col gap-4">
                    <div className="flex justify-between items-start">
                        <div className="font-code text-lg flex items-center gap-2">
                            <Server className="text-muted-foreground"/> {result.ipAddress}
                        </div>
                        <div className="text-sm text-muted-foreground flex items-center gap-1">
                            <MapPin className="size-4"/> {result.location}
                        </div>
                    </div>
                    <pre className="p-3 bg-black rounded-md text-white text-xs overflow-x-auto">
                        <code>{result.banner}</code>
                    </pre>
                    <div className="p-3 bg-destructive/10 border border-destructive/50 rounded-lg text-destructive-foreground flex items-start gap-3">
                        <AlertTriangle className="size-5 mt-1 flex-shrink-0"/>
                        <div className="text-sm">
                            <p className="font-semibold">Notes</p>
                            <p className="opacity-90">{result.notes}</p>
                        </div>
                    </div>
                </div>
            ))}
          </CardContent>
        </Card>
      )}
      
       {results && results.length === 0 && !isSearching && (
        <div className="text-center p-8">
            <p className="text-muted-foreground">No results found.</p>
        </div>
      )}
    </div>
  );
}
