import { config } from 'dotenv';
config();

import '@/ai/flows/vulnerability-assessment.ts';
import '@/ai/flows/exploit-suggestion.ts';
import '@/ai/flows/web-crawler.ts';
import '@/ai/flows/wordlist-suggestion.ts';
import '@/ai/flows/agent-chat.ts';
import '@/ai/flows/nmap-suggestion.ts';
import '@/ai/flows/generate-breached-passwords.ts';
import '@/ai/flows/check-password-strength.ts';
import '@/ai/flows/content-authenticity.ts';
import '@/ai/flows/run-llama-tool.ts';
import '@/ai/flows/attack-surface-mapper.ts';
import '@/ai/flows/vulndb-explorer.ts';
import '@/ai/flows/default-pass.ts';
import '@/ai/flows/text-to-speech.ts';
import '@/ai/flows/threat-view.ts';
import '@/ai/flows/data-sieve.ts';
import '@/ai/flows/network-scan.ts';
import '@/ai/flows/cve-monitor.ts';
import '@/ai/flows/fofa-suggestion.ts';
